package no.siriuslabs.computationapi.api.model.request;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import no.siriuslabs.computationapi.api.model.computation.DomainType;
import no.siriuslabs.computationapi.api.model.computation.DomainTypeToStringConverter;
import no.siriuslabs.computationapi.api.model.computation.StringToDomainTypeConverter;

/**
 * Container class representing a computation request which sets off the computation process in the system.<p>
 * The request contains the initial information required to start a computation run. This data is the DomainType the data belongs to and a Payload object which contains the domain specific data.
 * It also can contain some statistical information which will be added when available later in the computation process.
 */
public class ComputationRequest {

	/**
	 * The DomainType that should be used for computing this request.
	 */
	@JsonSerialize(converter = DomainTypeToStringConverter.class)
	@JsonDeserialize(converter = StringToDomainTypeConverter.class)
	private DomainType domain;

	/**
	 * Payload object containing domain specific data needed for the process.
	 */
	private Payload payload;

	/**
	 * Timestamp the computation run started.
	 */
	private long startedTimestamp;
	/**
	 * Amount of time taken to perform the data preparation step (prepareAndPackageData).
	 */
	private long preparationTime;
	/**
	 * Number of WorkerNodes available at the beginning of the computation run (after the preparation step).
	 */
	private int numberNodesStart;
	/**
	 * Overall number of unique WorkPackages generated by the preparation step.
	 */
	private int numberWPs;

	/**
	 * Constructor needed for de-serialization.
	 */
	public ComputationRequest() {
	}

	public DomainType getDomain() {
		return domain;
	}

	public void setDomain(DomainType domain) {
		this.domain = domain;
	}

	public Payload getPayload() {
		return payload;
	}

	public void setPayload(Payload payload) {
		this.payload = payload;
	}

	public long getStartedTimestamp() {
		return startedTimestamp;
	}

	public void setStartedTimestamp(long startedTimestamp) {
		this.startedTimestamp = startedTimestamp;
	}

	public long getPreparationTime() {
		return preparationTime;
	}

	public void setPreparationTime(long preparationTime) {
		this.preparationTime = preparationTime;
	}

	public int getNumberNodesStart() {
		return numberNodesStart;
	}

	public void setNumberNodesStart(int numberNodesStart) {
		this.numberNodesStart = numberNodesStart;
	}

	public int getNumberWPs() {
		return numberWPs;
	}

	public void setNumberWPs(int numberWPs) {
		this.numberWPs = numberWPs;
	}

	@Override
	public String toString() {
		return "ComputationRequest{" +
				"domain=" + domain +
				", payload=" + payload +
				'}';
	}
}
